# Generated by Django 4.2.23 on 2026-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="movie",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="tags",
            field=models.ManyToManyField(blank=True, to="movie.tag"),
        ),
    ]
