# Generated by Django 4.2.23 on 2026-06-29 16:48

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_tag_alter_movie_content_movie_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=movie.models.image_upload_path
            ),
        ),
    ]
